[package]
name = "jetstream-consumer"
version = "0.1.0"
edition = "2021"

[dependencies]
async-nats = "0.35.1"
bytes = "1.7.1"
futures = "0.3.30"
tokio = { version = "1.39.3", features = ["full"] }
tracing = "0.1.40"
